### ISSUE TITLE
Azure notebook link opens in wrong library

### ISSUE THREAD

**Issue by mikecroucher** [trallard/Modules-template#10]
This notebook http://bitsandchips.me/Modules-template/Day1/basic_classification/
The Azure link opens the BAD days Azure library.

Perhaps we could have a separate Azure library just for the demo page of the template?  It could include a random selection of notebooks BAD Days, GpY, Something from Julia, etc.

I'll be showing off the template tomorrow in Naples so I'm really grateful for the demo course you've done :)

**Comment by trallard** [comment]
oh I hardcoded this to have *one* Azure library per site... could always explore ways to have multiple ones
